# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 20:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('OF', 'Oficinas'), ('CU', 'Cultura'), ('CA', 'Casas'), ('ED', 'Edificaciones'), ('JA', 'Jardines'), ('CO', 'Comunidad')], max_length=2, verbose_name='Nombre categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Descripción')),
                ('project_type', models.CharField(choices=[('I', 'Iluminación'), ('P', 'Paisajismo'), ('M', 'Mixto')], default='I', max_length=1, verbose_name='Tipo')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2016, 10, 18, 20, 32, 57, 11084, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategoryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sofiapp.Category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sofiapp.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(through='sofiapp.ProjectCategoryRelationship', to='sofiapp.Category'),
        ),
    ]
