# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 22:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, unique=True, verbose_name='Nombre categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('text', models.TextField(verbose_name='Descripción')),
                ('created_date', models.DateField(default=datetime.datetime(2016, 10, 24, 22, 9, 27, 460385, tzinfo=utc), verbose_name='Fecha de creación')),
                ('architecture', models.CharField(max_length=200, verbose_name='Arquitectura')),
                ('landscaping', models.CharField(max_length=200, verbose_name='Paisajismo')),
                ('location', models.CharField(max_length=200, verbose_name='Ubicación')),
                ('public', models.BooleanField(default=True, verbose_name='Proyecto público')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategoryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sofiapp.Category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sofiapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTypeM2M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sofiapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=200, unique=True, verbose_name='Tipo de proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='projecttypem2m',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sofiapp.Type'),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(through='sofiapp.ProjectCategoryRelationship', to='sofiapp.Category'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_types',
            field=models.ManyToManyField(through='sofiapp.ProjectTypeM2M', to='sofiapp.Type'),
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sofiapp.Project'),
        ),
    ]
