# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 22:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sofiapp', '0002_auto_20161018_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre categoría'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 18, 22, 7, 44, 258366, tzinfo=utc)),
        ),
    ]
