# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 00:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('sofiapp', '0002_auto_20161110_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='project_images/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2016, 11, 11, 0, 25, 36, 942467, tzinfo=utc), verbose_name='Fecha de creación'),
        ),
    ]
