# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 01:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sofiapp', '0003_auto_20161018_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 19, 1, 0, 13, 758315, tzinfo=utc)),
        ),
    ]
