# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sofiapp', '0004_auto_20161018_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/', verbose_name='Imagen')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 24, 16, 41, 10, 532807, tzinfo=utc), verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Proyecto público'),
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sofiapp.Project'),
        ),
    ]
